### ISSUE TITLE
Windows 10 SDK not found

### ISSUE THREAD

**Issue by rafagouveia** [Microsoft/reactxp#1023]
I'm trying to test the application in Windows 10, and I'm getting this error
"Windows SDK not found. Ensure that you have installed Windows 10.0 SDK along with Visual Studio or install Windows 10.0 SDK separately from https://dev.windows.com/en-us/downloads", but I have Visual Studio installed with all components for the development mobilel and tbm I installed the Windows 10 SDK.

> My Environment:
Windows 10 Pro - Build 1809
Windows 10 Sdk - Build 10.0.17763.0
Visual Studio Comunity 2017 - v15.9.6

```powershell
PS C:\APPS\AppName> npm run start:windows

> appname@0.0.1 start:windows C:\APPS\AppName
> yarn rn-cli run-windows

yarn run v1.13.0
$ node node_modules/react-native/local-cli/cli.js run-windows
Restoring NuGet packages
Building C:/APPS/AppName/windows/AppName.sln
Found MSBuild v15.0 at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin
Building Solution: C:/APPS/AppName/windows/AppName.sln
Build configuration: Debug
Build platform: x86
'reg' not recognized as an internal command
or external, an operable program or a batch file.

> Windows SDK not found. Ensure that you have installed Windows 10.0 SDK along with Visual Studio or install Windows 10.0 SDK separately from https://dev.windows.com/en-us/downloads

Starting the React-Native Server
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appname@0.0.1 start:windows: `yarn rn-cli run-windows`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appname@0.0.1 start:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rafael Gomes\AppData\Roaming\npm-cache\_logs\2019-02-05T20_04_20_238Z-debug.log
PS C:\APPS\AppName>
```

### any solution?

**Comment by rafagouveia** [comment]
**Reinstall resolved**
