### ISSUE TITLE
Cant run samples target:windows

### ISSUE THREAD

**Issue by dviluk** [microsoft/reactxp#1110]
Hello everyone, i can run all platforms but windows.

Here are the errors.

**I have SDK 10586, 14393 and 17134**

#### On TodosList sample:

```shell
1>------ Skipped Build: Project: ChakraBridge, Configuration: Debug Win32 ------
1>Project not selected to build for this solution configuration 
2>------ Skipped Build: Project: ReactNativeWebViewBridge, Configuration: Debug x86 ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: yoga.uwp, Configuration: Debug Win32 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Build: Project: ReactNative, Configuration: Debug x86 ------
4>Project not selected to build for this solution configuration 
NU1605: Detected package downgrade: Microsoft.NETCore.UniversalWindowsPlatform from 6.0.6 to 6.0.4. Reference the package directly from the project to select a different version. 
 TodoList -> ReactNative -> Microsoft.NETCore.UniversalWindowsPlatform (>= 6.0.6) 
 TodoList -> Microsoft.NETCore.UniversalWindowsPlatform (>= 6.0.4)
NU1605: Detected package downgrade: Microsoft.NETCore.UniversalWindowsPlatform from 6.0.6 to 5.2.2. Reference the package directly from the project to select a different version. 
 SQLitePlugin -> ReactNative -> Microsoft.NETCore.UniversalWindowsPlatform (>= 6.0.6) 
 SQLitePlugin -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2)
5>------ Build started: Project: SQLitePlugin, Configuration: Debug Any CPU ------
5>CSC : error CS0006: Metadata file 'W:\reactxp\TodoList\node_modules\react-native-windows\ReactWindows\ReactNative\bin\x86\Debug\ReactNative.dll' could not be found
6>------ Skipped Build: Project: TodoList, Configuration: Debug x86 ------
6>Project not selected to build for this solution configuration 
7>------ Skipped Deploy: Project: TodoList, Configuration: Debug x86 ------
7>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 5 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 1 skipped ==========

```

#### hello-world-js, hello-world
```shell
PS W:\reactxp\hello-world-js> yarn start:windows
yarn run v1.16.0
$ npm run rn-cli -- run-windows

> rxphelloworld@1.6.0 rn-cli W:\reactxp\hello-world-js
> node node_modules/react-native/local-cli/cli.js "run-windows"

Restoring NuGet packages
Build failed with message Error: Must have a minimum Windows SDK version 10.0.10586.0 installed. Check your build configuration.
Done in 6.27s.
PS W:\reactxp\hello-world-js>
```

#### hello-world-js, hello-world FROM Visual Studio

First time trying to run solution in Visual Studio
```shell
1>------ Build started: Project: ChakraBridge, Configuration: Debug x64 ------
2>------ Build started: Project: ReactNativeWebViewBridge, Configuration: Debug x64 ------
3>------ Build started: Project: yoga.uwp, Configuration: Debug x64 ------
3>Utils.cpp
3>YGConfig.cpp
3>YGEnums.cpp
1>pch.cpp
3>YGFloatOptional.cpp
3>YGLayout.cpp
3>YGNode.cpp
3>YGNodePrint.cpp
3>YGStyle.cpp
3>Yoga.cpp
3>YGInterop.cpp
3>stdafx.cpp
3>dllmain.cpp
3>   Creating library bin\Universal\x64\Debug\yoga.lib and object bin\Universal\x64\Debug\yoga.exp
3>Yoga.Universal.vcxproj -> W:\reactxp\hello-world-js\node_modules\react-native-windows\Yoga\csharp\Yoga\bin\Universal\x64\Debug\yoga.dll
2>  ReactNativeWebViewBridge -> W:\reactxp\hello-world-js\node_modules\react-native-windows\ReactWindows\ReactNativeWebViewBridge\bin\x64\Debug\ReactNativeWebViewBridge.winmd
3>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(5712,5): warning APPX1901: The DefaultLanguage property is either missing from the project file or does not have a value. The fallback language is set to the Visual Studio language: en-US.
1>asprintf.cpp
1>ChakraHost.cpp
1>JsIndexedModulesUnbundle.cpp
1>JsModulesUnbundle.cpp
1>NativeJavaScriptExecutor.cpp
3>Done building project "Yoga.Universal.vcxproj".
1>w:\reactxp\hello-world-js\node_modules\react-native-windows\reactwindows\chakrabridge\jsindexedmodulesunbundle.cpp(80): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data
1>w:\reactxp\hello-world-js\node_modules\react-native-windows\reactwindows\chakrabridge\nativejavascriptexecutor.cpp(53): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>w:\reactxp\hello-world-js\node_modules\react-native-windows\reactwindows\chakrabridge\nativejavascriptexecutor.cpp(106): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>w:\reactxp\hello-world-js\node_modules\react-native-windows\reactwindows\chakrabridge\nativejavascriptexecutor.cpp(134): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>w:\reactxp\hello-world-js\node_modules\react-native-windows\reactwindows\chakrabridge\nativejavascriptexecutor.cpp(153): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>   Creating library W:\reactxp\hello-world-js\windows\x64\Debug\ChakraBridge\ChakraBridge.lib and object W:\reactxp\hello-world-js\windows\x64\Debug\ChakraBridge\ChakraBridge.exp
1>ChakraBridge.vcxproj -> W:\reactxp\hello-world-js\windows\x64\Debug\ChakraBridge\ChakraBridge.dll
1>Done building project "ChakraBridge.vcxproj".
4>------ Build started: Project: ReactNative, Configuration: Debug x64 ------
4>W:\reactxp\hello-world-js\node_modules\react-native-windows\ReactWindows\ReactNative.Shared\DevSupport\DisabledDevSupportManager.cs(77,29,77,55): warning CS0067: The event 'DisabledDevSupportManager.BeforeShowDevOptionsDialog' is never used
4>W:\reactxp\hello-world-js\node_modules\react-native-windows\ReactWindows\ReactNative\obj\x64\Debug\XamlTypeInfo.g.cs(15,25,15,45): warning CS1591: Missing XML comment for publicly visible type or member 'XamlMetaDataProvider'
4>  ReactNative -> W:\reactxp\hello-world-js\node_modules\react-native-windows\ReactWindows\ReactNative\bin\x64\Debug\ReactNative.dll
5>------ Build started: Project: RXPHelloWorld, Configuration: Debug x64 ------
5>  RXPHelloWorld -> W:\reactxp\hello-world-js\windows\RXPHelloWorld\bin\x64\Debug\RXPHelloWorld.exe
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816: Loading assembly "C:\Users\dviluk\.nuget\packages\runtime.win7-x64.microsoft.netcore.runtime.coreclr\1.0.2\runtimes\win7-x64\native\mscorlib.ni.dll" failed. System.ArgumentException: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context. ---> System.BadImageFormatException: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816: 
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    --- End of inner exception stack trace ---
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    --- End of inner exception stack trace ---
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at Microsoft.Build.Tasks.ProcessResourceFiles.ReadAssemblyResources(String name, String outFileOrDir)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816: Loading assembly "C:\Users\dviluk\.nuget\packages\runtime.win7-x64.microsoft.netcore.runtime.coreclr\1.0.2\runtimes\win7-x64\lib\netstandard1.0\mscorlib.dll" failed. System.ArgumentException: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context. ---> System.BadImageFormatException: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816: 
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    --- End of inner exception stack trace ---
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    --- End of inner exception stack trace ---
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
5>P:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1248,5): error MSB3816:    at Microsoft.Build.Tasks.ProcessResourceFiles.ReadAssemblyResources(String name, String outFileOrDir)
========== Build: 4 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

```

Second time, project start correctly but there is a problem with an import related to react-native-windows and react-native,

```shell
error: bundling failed: Error: Unable to resolve module `ColorPropType` from `w:\reactxp\hello-world-js\node_modules\react-native-windows\Libraries\Components\ActivityIndicator\ActivityIndicator.windows.js`: Module `ColorPropType` does not exist in the Haste module map
```

 ColorPropType is deprecated in react-native@0.59 and solved in react-native-windows@0.58,  i made the changes but still got another error

```shell
Assembly 'System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=957107be965c25d9' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.
```

Updating to latest version of System.Reactive and Newtonsoft.Json does not solve anything :c 

i tried all
https://github.com/Microsoft/react-native-windows/issues/1597
https://github.com/microsoft/react-native-windows/issues/1954
https://github.com/microsoft/react-native-windows/issues/1593

thankyou!

**Comment by dviluk** [comment]
Oh i see https://github.com/microsoft/reactxp/commit/d1f31497289d79115891c9558e7f48b08fc1d467 still working to support RN0.59, my bad, i just downloaded master without knowing this
