### ISSUE TITLE
ScrollView crashing in non-browser environments

### ISSUE THREAD

**Issue by Joeao** [microsoft/reactxp#1185]
Hi Team ReactXP.

Doing some server side rendering and getting a `document is not defined` error. This problem seems to be similar to #730, fixed by  https://github.com/microsoft/reactxp/commit/7e067947ff3fab585dea3f40d5715687240f5206.

The issue can be replicated by rendering a `ScrollView` element in a non-browser environment. In my particular use case I'm using `ReactDOMServer.renderToString`, rendering a ReactXP app which includes a `ScrollView`.

```
 ReferenceError: document is not defined
    at Function.Scrollbar.getNativeScrollbarWidth (node_modules/reactxp/dist/web/CustomScrollbar.js:45:21)
    at new ScrollView (node_modules/reactxp/dist/web/ScrollView.js:147:66)
```
https://github.com/microsoft/reactxp/blob/master/src/web/CustomScrollbar.ts#L187
https://github.com/microsoft/reactxp/blob/master/src/web/ScrollView.tsx#L88

**Comment by fbartho** [comment]
It looks like you've already fixed this, so I'm going to close this ticket. Please reply back @Joeao if there's more that needs to be done!

**Comment by fbartho** [comment]
Actually, I now realize that you've fixed this in a fork of reactxp -- is this something you'd like to contribute back to core? Is there a performance implication or other risk to what you changed?
