### ISSUE TITLE
Sample TODO app does not build 

### ISSUE THREAD

**Issue by SeanDunford** [microsoft/reactxp#1228]
**Steps to reproduce**
1. pull code 
2. cd into `./samples/TodoList`
3. npm install 

**What did you expect to happen**
Sample app to install and run successfully 

**What actually happened?**
![image](https://user-images.githubusercontent.com/1704718/89546786-f7e05680-d7d2-11ea-9087-43bf3b252abd.png)

```
cat  /Users/seandunford/.npm/_logs/2020-08-06T05_53_23_085Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@6.14.5
3 info using node@v12.17.0
4 verbose npm-session 6e42e7abc1a6b243
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall todolist@2.0.0
7 info lifecycle todolist@2.0.0~preinstall: todolist@2.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 11ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 warn conflict A git conflict was detected in package-lock.json. Attempting to auto-resolve.
16 warn conflict To make this happen automatically on git rebase/merge, consider using the npm-merge-driver:
17 warn conflict $ npx npm-merge-driver install -g
18 error conflict Automatic conflict resolution failed. Please manually resolve conflicts in package-lock.json and try again.
19 silly conflict Error during resolution: SyntaxError: Unexpected string in JSON at position 741059 while parsing '{    "name": "todolist",    "version": "'
20 timing stage:rollbackFailedOptional Completed in 0ms
21 timing stage:runTopLevelLifecycles Completed in 54ms
22 silly saveTree todolist@2.0.0
23 verbose stack SyntaxError: Unexpected token < in JSON at position 165732 while parsing near '...       }
23 verbose stack         },
23 verbose stack <<<<<<< HEAD
23 verbose stack        ...'
23 verbose stack     at JSON.parse (<anonymous>)
23 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
23 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/utils/parse-json.js:4:10)
23 verbose stack     at parsePkgLock (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:67:12)
23 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:27:22
23 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
23 verbose stack     at Holder$2._callFunction (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:12:44)
23 verbose stack     at Holder$2.checkFulfillment (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:27:30)
23 verbose stack     at Promise.eval (eval at thenCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:4:20)
23 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:571:21)
23 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
23 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
23 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:643:18)
23 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:587:21)
23 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
23 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
24 verbose cwd /Users/seandunford/projects/reactxp/samples/TodoList
25 verbose Darwin 19.6.0
26 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
27 verbose node v12.17.0
28 verbose npm  v6.14.5
29 error Unexpected token < in JSON at position 165732 while parsing near '...       }
29 error         },
29 error <<<<<<< HEAD
29 error        ...'
30 verbose exit [ 1, true ]
```

**Comment by mikehardy** [comment]
Oh no @seandunford - I think if you `rm package-lock.json` and try again it will work for you without any further hold up

There is definitely a conflict committed to the git repository though, which I will post a PR to fix
