### ISSUE TITLE
JS Exception on Android version of samples

### ISSUE THREAD

**Issue by msaglietto** [Microsoft/reactxp#494]
Hello

I cloned the repo and I was trying to run the samples .. In web they run just fine..

On Android Emulator running API 27 when I try to run them I got the following exception:

Hello-world got this exception at the start

```
E/ReactNativeJNI: Got JS Exception: Map constructor does not accept arguments (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26852)
E/ReactNativeJNI: Got JS Stack: Map@[native code]
                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26852:45
                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:27120:9
                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:27122:10
                  __webpack_require__@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:1309:27
                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:1349:43
                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:1351:10
                  __webpack_require__@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:1309:27
                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:30836:34
                  __webpack_require__@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:1309:27
                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:2407:39
                  __webpack_require__@http://10.0.2.2:80
E/unknown:ReactNative: Exception in native call from JS
                       com.facebook.react.devsupport.JSException: Map constructor does not accept arguments (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26852)
                           at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                           at android.os.Handler.handleCallback(Handler.java:790)
                           at android.os.Handler.dispatchMessage(Handler.java:99)
                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                           at android.os.Looper.loop(Looper.java:164)
                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                           at java.lang.Thread.run(Thread.java:764)
                        Caused by: com.facebook.jni.CppException: Map constructor does not accept arguments (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&minify=false:26852)
                           at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                           at android.os.Handler.handleCallback(Handler.java:790) 
                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                           at android.os.Looper.loop(Looper.java:164) 
                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
                           at java.lang.Thread.run(Thread.java:764) 
E/unknown:ReactNative: Exception in native call
                       java.lang.RuntimeException: Error calling AppRegistry.runApplication
                           at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                           at android.os.Handler.handleCallback(Handler.java:790)
                           at android.os.Handler.dispatchMessage(Handler.java:99)
                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                           at android.os.Looper.loop(Looper.java:164)
                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                           at java.lang.Thread.run(Thread.java:764)
                        Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                           at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                           at android.os.Handler.handleCallback(Handler.java:790) 
                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                           at android.os.Looper.loop(Looper.java:164) 
                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
                           at java.lang.Thread.run(Thread.java:764) 
```
I read somewhere you need the babel-pollyfill but that give you another error  saying document is not defined what make sense react-native dont have a document

RXPTest got this exception when you click on "see more examples"
```
E/ReactNativeJS: Invariant Violation: Native component for "RNSVGSvgView" does not exist

                 This error is located at:
                     in RNSVGPath (at Path.js:25)
                     in Path (created by SvgPath)
                     in SvgPath (created by ProgressIndicator)
                     in RNSVGSvgView (at Svg.js:80)
                     in Svg (created by ImageSvg)
                     in ImageSvg (created by ProgressIndicator)
                     in ProgressIndicator (created by SecondPanel)
                     in RCTView (at View.js:112)
                     in View (created by View)
                     in View (created by SecondPanel)
                     in RCTView (at View.js:112)
                     in View (at ScrollView.js:748)
                     in RCTScrollView (at ScrollView.js:857)
                     in ScrollView (created by ScrollView)
                     in ScrollView (created by SecondPanel)
                     in SecondPanel (created by SceneView)
                     in SceneView (at NavigationCard.js:141)
                     in RCTView (at View.js:112)
                     in View (at createAnimatedComponent.js:134)
                     in AnimatedComponent (at NavigationCard.js:135)
                     in NavigationCard (at NavigationPointerEventsContainer.js:92)
                     in Container (at NavigationCardStack.js:345)
                     in RCTView (at View.js:112)
                     in View (at NavigationCardStack.js:310)
                     in RCTView (at View.js:112)
                     in View (at NavigationCardStack.js:309)
                     in RCTView (at View.js:112)
                     in View (at NavigationTransitioner.js:232)
                     in NavigationTransitioner (at NavigationCardStack.js:254)
                     in NavigationCardStack (created by NavigatorImpl)
                     in NavigatorImpl (created by App)
                     in App
                     in RCTView (at View.js:112)
                     in View (created by RootViewUsingStore)
                     in RCTView (at View.js:112)
                     in View (at createAnimatedComponent.js:134)
                     in AnimatedComponent (created by RootViewUsingStore)
                     in RootViewUsingStore (at renderApplication.js:35)
                     in RCTView (at View.js:112)
                     in View (at AppContainer.js:102)
                     in RCTView (at View.js:112)
                     in View (at AppContainer.js:122)
                     in AppContainer (at renderApplication.js:34)
E/unknown:ReactNative: Exception in native call
                       com.facebook.react.uimanager.IllegalViewOperationException: No ViewManager defined for class RNSVGPath
                           at com.facebook.react.uimanager.ViewManagerRegistry.get(ViewManagerRegistry.java:59)
                           at com.facebook.react.uimanager.UIImplementation.createShadowNode(UIImplementation.java:130)
                           at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:277)
                           at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:373)
                           at java.lang.reflect.Method.invoke(Native Method)
                           at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                           at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                           at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                           at android.os.Handler.handleCallback(Handler.java:790)
                           at android.os.Handler.dispatchMessage(Handler.java:99)
                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                           at android.os.Looper.loop(Looper.java:164)
                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                           at java.lang.Thread.run(Thread.java:764)
```

So the steps should be 
1. Clone repo
2. Go to sample folder
3. run `npm install`
4. run `npm run rn-watch`
5. run `npm start` on another terminal
6. Open android project on android studio
7. run android emulator

Am I missing something?

**Comment by erictraut** [comment]
I'm not sure why you're hitting the first problem.

For the second problem, it looks like you're running the packager in the hello-world directory. The hello-world example makes use of reactxp-imagesvg. But you're running the native project associated with RXPTest, which doesn't include the RNSvg module. You need to restart the packager within the RXPTest directory so the correct JS bundle gets packaged and sent to the app.

**Comment by erictraut** [comment]
@msaglietto, were you able to figure out the problem?

**Comment by msaglietto** [comment]
no sorry I was not able to figure out why was not working

**Comment by erictraut** [comment]
I don't usually use the Android simulator because I find that it's incredibly flakey even on a good day. I usually use a connected physical device.

I just tried to replicate your problem using an API 27 (Pixel) image in the simulator, and it worked fine for me.

A few things for you to try:
1. Switch from the hello-world to the RXPTest sample. The latter doesn't require any added react native extensions, so it's simpler. 
2. Switch from the Android simulator to a physical device. You'll need to enable USB debugging on the device and run the command "adb reverse tcp:8081 tcp:8081" to set up the debugger listener.

**Comment by msaglietto** [comment]
Well I was able to run it on the device .. but its not ideal =(

**Comment by erictraut** [comment]
Yeah, the Android simulator is not great. Don't know what to tell you. The iOS simulator is much more reliable.
