### ISSUE TITLE
react-native 0.54.x AnimatedComponent + Jest API compatibility issue

### ISSUE THREAD

**Issue by fbartho** [Microsoft/reactxp#548]
When using `ReactXP 1.0.1` with `react-native 0.54.2` and running unit tests, I noticed that `RX.Button` uses a property that isn't available when running react-native under jest.

<details>
<summary><b>Example Error Log</b></summary>

```bash
    console.error scripts/jest/beforeAll.js:52
      The above error occurred in the <AnimatedComponent> component:
          in AnimatedComponent (created by Button)
          in Button (created by StylingLoader)
          in View (created by View)
          in View (created by View)
          in View (created by StylingLoader)
          in StylingLoader (created by StylingLoader[account.settings.savebutton])
          in StylingLoader[account.settings.savebutton] (created by AccountSettingsSaveButton)
          in AccountSettingsSaveButton (created by StylingLoader)
          in View (created by View)
          in View (created by View)
          in View (created by StylingLoader)
          in View (created by View)
          in View (created by View)
          in View (created by StylingLoader)
          in StylingLoader (created by StylingLoader[account.settings])
          in StylingLoader[account.settings] (created by AccountSettings)
          in AccountSettings (created by DemoAccountSettingsOverloaded)
          in DemoAccountSettingsOverloaded
          in SelectTextStyles (created by TestPresentationalBootstrap)
          in SelectColorPalette (created by TestPresentationalBootstrap)
          in AnalyticsRootProvider (created by ServerConsumer)
          in ServerConsumer (created by EnvironmentConsumer)
          in EnvironmentConsumer (created by AnalyticsRoot)
          in AnalyticsRoot (created by TestPresentationalBootstrap)
          in ServerProvider_ (created by EnvironmentConsumer)
          in EnvironmentConsumer (created by ServerProvider)
          in ServerProvider (created by TestPresentationalBootstrap)
          in ViewportProvider (created by TestPresentationalBootstrap)
          in ContextSignalComponent (created by TestPresentationalBootstrap)
          in IntlProvider (created by TestPresentationalBootstrap)
          in EnvironmentProvider
          in Unknown (created by TestPresentationalBootstrap)
          in TestPresentationalBootstrap

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● renders account-settings for example data

    TypeError: Cannot read property '__getValue' of undefined

      at AnimatedComponent.render (node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:1:4815)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3656:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3633:12)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4008:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6007:16)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6071:26)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1559:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1506:29)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6149:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6797:24)
```
</details><br/>

Note: the top-level `Button` in this is `RX.Button` our app doesn't yet use `AnimatedComponent` directly. -- I'm not sure if this is ReactXP poking at private member variables / non-public API or if Facebook changed a public detail.

**Comment by erictraut** [comment]
@berickson1, is this caused by the bug you fixed yesterday in the Button implementation?

**Comment by berickson1** [comment]
I don't believe so. I was addressing an issue discovered in our app. I
didn't touch anything related to animated components.

**Comment by erictraut** [comment]
@fbartho, do you have any more details — in particular, which property it's trying to access? We use an AnimatedComponent internally to the RX.Button implementation (to animate the opacity change when the user taps). To the best of my knowledge, we're using only documented props. It's possible this is a bug in Jest.

**Comment by fbartho** [comment]
It's trying to access `__getValue` of some undefined object, I have no idea what that object is, possibly some underlying Animated impl or something? -- I won't be online this weekend, but I can possibly chase it down on Monday.

**Comment by fbartho** [comment]
This is still occurring on
```
"react": "16.3.0",,
"react-native": "0.54.x",
```

I'm trying to monkey-patch createAnimatedComponent.js to see if I can fix it. But I think the problem is using AnimatedComponent in button impl!

**Comment by fbartho** [comment]
It looks like the root bug is in `react-test-renderer` and that it doesn't support `UNSAFE_` prefixed methods, yet.

**Comment by fbartho** [comment]
Turns out there was a new update to `react-test-renderer`, and my yarn didn't upgrade to it! Problem solved.
