### ISSUE TITLE
Web-watch failing (TypeError: Cannot read property '_tsInstances' of undefined)

### ISSUE THREAD

**Issue by degroote22** [Microsoft/reactxp#609]
Using the current examples ([forked on this tree](https://github.com/Microsoft/reactxp/tree/c9a8af0232859c4205414d9319fceb5803c0c883)) I'm getting a lot of these errors when I update the code and it would recompile.

`
/any/node_modules/awesome-typescript-loader/src/instance.ts:73
	if (!compiler._tsInstances) {
               ^
TypeError: Cannot read property '_tsInstances' of undefined
    at resolveInstance (/any/node_modules/awesome-typescript-loader/src/instance.ts:73:16)
    at /any/node_modules/awesome-typescript-loader/src/instance.ts:368:20
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/any/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:16:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/any/node_modules/tapable/lib/Hook.js:35:21)
    at Watching._go (/any/node_modules/webpack/lib/Watching.js:40:32)
    at Watching._invalidate (/any/node_modules/webpack/lib/Watching.js:164:9)
    at watcher.compiler.watchFileSystem.watch (/any/node_modules/webpack/lib/Watching.js:135:10)
    at Watchpack.watcher.once (/any/node_modules/webpack/lib/node/NodeWatchFileSystem.js:43:4)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Watchpack.emit (events.js:214:7)
    at Watchpack._onTimeout (/any/node_modules/watchpack/lib/watchpack.js:142:7)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
`

[It's a known](https://github.com/s-panferov/awesome-typescript-loader/issues/534) [issue of awesome-typescript-loader.](https://github.com/s-panferov/awesome-typescript-loader/issues/541)

Upgrading this library to version 5.0.0 fixed the problem for **me** [but it seems that the fix is not stable.](https://github.com/s-panferov/awesome-typescript-loader/issues/560#issuecomment-376132744)

I won't submit a PR for now because I don't know if upgrading is what should be done and I believe the current test cases on CI wouldn't catch any regression on assure this problem is fixed.
Thanks for your time :)

**Comment by a-tarasyuk** [comment]
@erictraut As `awesome-typescript-loader` + `webpack 4.*` does not work properly, maybe make sense to use `ts-loader`. It works pretty well with `webpack 4.*` and supports performance improvements [ts-loader#faster-builds](https://github.com/TypeStrong/ts-loader#faster-builds)(I think, for simple samples, it is not critical). What do you think about this case? If it OK for you, I'll make PR.

**Comment by degroote22** [comment]
It seems that the fix [is now stable](https://github.com/s-panferov/awesome-typescript-loader/compare/v5.0.0-0...master), since the issue that the user referenced on the comment I linked happened before the fix was comitted to support Windows (the reason the fix was unstable).

However, users on their issue tracker have reported this issue happening after the fix but it's hard to know if they were using the latest version when they got the error.

Have you been getting this error too?
I forgot to tell on my first post but I only tested it on Ubuntu 16, Node 6, NPM 4.
I'd break half the time before the update and has never broken after.

**Comment by erictraut** [comment]
I'm able to repro the problem with awesome-typescript-loader 4.0.1. When I update it to 5.0.0, the problem goes away.
