### ISSUE TITLE
Can't run sample hello world: "Unable to load script from assets 'index.android.bundle'"

### ISSUE THREAD

**Issue by gabrielenosso** [Microsoft/reactxp#650]
I cloned the "reactxp" repo, I went into the folder "reactxp/samples/hello-world" and I run:
```
npm install
npm run android
```
It launches the metro bundler on another prompt, then builds the package.
It starts the app in the Android emulator, but it shows a red screen with the following error:
```
Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
```

I tried to open the "android" folder in Android Studio and run the project, and I got the same error:
```

05/30 16:50:36: Launching app
$ adb install-multiple -r -t C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\dep\dependencies.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_1.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_2.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_4.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_3.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_6.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_0.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_5.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_7.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_8.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\split-apk\debug\slices\slice_9.apk C:\Users\Zedstar\CODE\reactxp\samples\hello-world\android\app\build\intermediates\instant-run-apk\debug\app-debug.apk 
Split APKs installed
$ adb shell am start -n "com.rxphelloworld/com.rxphelloworld.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Connected to process 18166 on device Nexus_5X_API_25 [emulator-5554]
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/art: Not late-enabling -Xcheck:jni (already on)
I/InstantRun: starting instant run server: is main process
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.rxphelloworld/lib-main
V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
V/fb-UnpackingSoSource: so store dirty: regenerating
D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libfb.so: deferring to libdir
               not allowing consideration of lib/armeabi-v7a/libfolly_json.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libglog.so: deferring to libdir
               not allowing consideration of lib/armeabi-v7a/libglog_init.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libgnustl_shared.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libicu_common.so: deferring to libdir
               not allowing consideration of lib/armeabi-v7a/libimagepipeline.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libjsc.so: deferring to libdir
               not allowing consideration of lib/armeabi-v7a/libprivatedata.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libreactnativejni.so: deferring to libdir
D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libyoga.so: deferring to libdir
V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
V/fb-UnpackingSoSource: starting syncer worker
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.rxphelloworld/lib-main (from syncer thread)
V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.rxphelloworld/lib-main (syncer thread started)
D/ReactNative: ReactInstanceManager.ctor()
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/ReactNative: ReactInstanceManager.createReactContextInBackground()
D/ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
W/art: Verification of okhttp3.Response okhttp3.internal.cache.CacheInterceptor.intercept(okhttp3.Interceptor$Chain) took 102.784ms
W/art: Verification of okhttp3.internal.connection.RealConnection okhttp3.internal.connection.StreamAllocation.findConnection(int, int, int, boolean) took 131.138ms
D/: HostConnection::get() New Host Connection established 0xed2fa2a8, tid 18201
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0xe1dfdf80: maj 3 min 1 rcv 4
D/EGL_emulation: eglMakeCurrent: 0xe1dfdf80: ver 3 1 (tinfo 0xe1dbc500)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
W/art: Verification of boolean okhttp3.internal.connection.RouteSelector.hasNext() took 108.985ms
D/EGL_emulation: eglMakeCurrent: 0xe1dfdf80: ver 3 1 (tinfo 0xe1dbc500)
W/art: Verification of void okhttp3.internal.connection.RealConnection.connect(int, int, int, boolean, okhttp3.Call, okhttp3.EventListener) took 104.587ms
W/art: Verification of void com.facebook.react.devsupport.InspectorPackagerConnection$Connection.onOpen(okhttp3.WebSocket, okhttp3.Response) took 314.504ms
W/art: Verification of void com.facebook.react.packagerconnection.JSPackagerClient.onMessage(java.lang.String) took 961.686ms
W/unknown:ReactNative: The packager does not seem to be running as we got an IOException requesting its status: connect timed out
D/ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
D/ReactNative: ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
I/art: Thread[17,tid=18251,Native,Thread*=0xe671c200,peer=0x12d4d940,"Thread-4"] recursive attempt to load library "/data/app/com.rxphelloworld-1/lib/arm/libfb.so"
D/ReactNative: ReactInstanceManager.createReactContext()
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.brentvatne.exoplayer.ReactExoplayerViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RenderableViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.GroupShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.PathShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.CircleShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.EllipseShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.LineShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RectShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.TextShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.TSpanShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.TextPathShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.ImageShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.ClipPathShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.DefsShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.UseShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.SymbolShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.LinearGradientShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.RadialGradientShadowNode
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.SvgViewManager
W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.horcrux.svg.SvgViewShadowNode
D/ReactNative: Initializing React Xplat Bridge.
D/ReactNative: Initializing React Xplat Bridge before initializeBridge
D/ReactNative: Initializing React Xplat Bridge after initializeBridge
D/ReactNative: CatalystInstanceImpl.runJSBundle()
E/unknown:ReactNative: Exception in native call
                       java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
                           at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
                           at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
                           at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:33)
                           at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:234)
                           at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1113)
                           at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
                           at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920)
                           at java.lang.Thread.run(Thread.java:761)
W/art: Suspending all threads took: 125.037ms
I/art: Background sticky concurrent mark sweep GC freed 29698(4MB) AllocSpace objects, 3(76KB) LOS objects, 35% free, 5MB/8MB, paused 130.466ms total 3.499s
W/art: Verification of void okhttp3.internal.ws.RealWebSocket.<init>(okhttp3.Request, okhttp3.WebSocketListener, java.util.Random) took 415.155ms
W/art: Verification of void okhttp3.internal.ws.RealWebSocket.failWebSocket(java.lang.Exception, okhttp3.Response) took 1.021s
W/art: Verification of void okhttp3.internal.ws.RealWebSocket$2.onResponse(okhttp3.Call, okhttp3.Response) took 121.682ms
W/art: Verification of boolean com.facebook.react.modules.camera.ImageEditingManager$CleanTask$1.accept(java.io.File, java.lang.String) took 241.045ms
I/Choreographer: Skipped 614 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation: eglMakeCurrent: 0xe1dfdf80: ver 3 1 (tinfo 0xe1dbc500)
E/OpenGLRenderer: Corrupted GPU pixel buffer
W/unknown:ReconnectingWebSocket: Couldn't connect to "ws://10.0.2.2:8081/message?device=Android%20SDK%20built%20for%20arm64%20-%207.1.1%20-%20API%2025&app=com.rxphelloworld&clientid=DevSupportManagerImpl", will silently retry
W/unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
W/unknown:ReconnectingWebSocket: Couldn't connect to "ws://10.0.2.2:8081/message?device=Android%20SDK%20built%20for%20arm64%20-%207.1.1%20-%20API%2025&app=com.rxphelloworld&clientid=DevSupportManagerImpl", will silently retry
E/unknown:ReactNative: Could not open stack frame
                       java.net.SocketTimeoutException: connect timed out
                           at java.net.PlainSocketImpl.socketConnect(Native Method)
                           at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
                           at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
                           at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
                           at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
                           at java.net.Socket.connect(Socket.java:605)
                           at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:70)
                           at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
                           at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
                           at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
                           at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
                           at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
                           at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                           at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                           at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                           at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                           at okhttp3.RealCall.execute(RealCall.java:77)
                           at com.facebook.react.devsupport.RedBoxDialog$OpenStackFrameTask.doInBackground(RedBoxDialog.java:215)
                           at com.facebook.react.devsupport.RedBoxDialog$OpenStackFrameTask.doInBackground(RedBoxDialog.java:192)
                           at android.os.AsyncTask$2.call(AsyncTask.java:305)
                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                           at java.lang.Thread.run(Thread.java:761)
I/art: Do partial code cache collection, code=30KB, data=30KB
I/art: After code cache collection, code=30KB, data=30KB
       Increasing code cache capacity to 128KB
I/art: Background partial concurrent mark sweep GC freed 27828(1135KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 5MB/8MB, paused 4.807ms total 160.199ms
```

**Comment by gabrielenosso** [comment]
I forgot to mention that also the web version doesn't work (and maybe that's the real problem).

If I run "npm run web-watch", it gives me the following errors:

```
ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:6208:55
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:6215:55
    TS2304: Cannot find name 'Set'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:6219:64
    TS2304: Cannot find name 'Symbol'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:6225:59
    TS2304: Cannot find name 'WeakMap'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:6226:59
    TS2304: Cannot find name 'WeakSet'.
```

**Comment by erictraut** [comment]
Please refer to the instructions [here](https://github.com/Microsoft/reactxp/tree/master/samples/hello-world). You need to run ```npm run rn-watch```.

**Comment by gabrielenosso** [comment]
But the sample doesn't work with "es5".
It doesn't start.

**Comment by erictraut** [comment]
OK, I'm able to repro the problem. Something must have changed with one of the dependent modules recently because this worked fine last week. I'll investigate further. Thanks for reporting the problem.

**Comment by erictraut** [comment]
I was able to fix by adding a new lib dependency in the tsconfig file. I left the target at es5. If you pull the latest sample code, it should work now.

**Comment by a-tarasyuk** [comment]
This issue related to the latest `@types/node` package `(10.*)`. In order to use `@types/node >= 10.0.0` need to add to `lib` values `es2015.collection`, `es2015.symbol` or include entire es6/es2015 featues.
```json
lib: ["es5", "dom", "es6"]
```

```json
lib: ["es5", "dom", "es2015.collection", "es2015.symbol"]
```

This issue can be reproduced in `samples/hello-world` because `node` types were specified in `"types"` property

```json
"types": [
    "node"
]
```
however, seems that these types useless here, because application`(src/*)` does not use any node types/features., We can remove `@types/node` from `package.json`. `tsconfig.json` can be changed like so
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "noImplicitReturns": true,
    "reactNamespace": "RX",
    "noImplicitAny": true,
    "declaration": false,
    "sourceMap": true,
    "noResolve": false,
    "module": "commonjs",
    "target": "es5",
    "outDir": "dist",
    "types": [],
    "jsx": "react",
  },

  "include": [
    "./src/**/*"
  ]
}
```

**Note** about `"types": []`. Need to be careful removing "types" property, because if it was not added in `tsconfig.json` `TS` includes all types from `node_modules/@types` and some packages include `@types/node` as dependency, for instance `webpack`

```json
"@types/webpack": {
      "version": "4.4.0",
      "resolved": "https://registry.npmjs.org/@types/webpack/-/webpack-4.4.0.tgz",
      "dev": true,
      "requires": {
        "@types/node": "10.1.2",
        "@types/tapable": "1.0.2",
        "@types/uglify-js": "3.0.2",
        "source-map": "0.6.1"
      },
}
```

and this package will be added to `@types/` automatically, therefore better to specify `types` explicitly in order to avoid such issues.

**Comment by erictraut** [comment]
Thanks @a-tarasyuk, this is a good simplification.
